### ISSUE TITLE
conf_inherit_as_dict，可以进行节继承的配置文件读取

### ISSUE THREAD

**Issue by mindjun** [chinapnr/fishbase#119]
## 背景
- `conf_as_dict`方法支持从配置文件中把配置读取为字典并返回
- 项目中涉及多个环境时配置时，经常会有很多配置是重复的

## 步骤
- 定义可进行节继承的配置文件，规定 `:` 表示继承关系，例如`[test:base]`就表示 `test` 继承自 `base` 的配置。
- 使用`configparser`包的方法，对配置文件中的节进行读取
- 以如下配置文件为例
```python
test.conf
[base]
base_1=base1
base_2=base2

[db]
host=localhost
port=3306

[testing:base:db]
name=test
```

## 实现
```python
>>> conf_file_path = '../file_info/test.conf'
>>> conf_dict = conf_inherit_as_dict(conf_file_path)
>>> conf_dict
OrderedDict([('base', OrderedDict([('base_1', 'base1'), ('base_2', 'base2')])),
             ('db', OrderedDict([('host', 'localhost'), ('port', '3306')])),
             ('testing', OrderedDict([('base_1', 'base1'), ('base_2', 'base2'),
                                      ('host', 'localhost'), ('port', '3306'), ('name', 'test')]))])
```

**Comment by wingfish** [comment]
[test:base] 表示test节的配置可以继承base的配置
这个写法很不好，为什么不是 base.test，这样表示 base 是 test 的父对象，

然后举例中的 [testing:base:db] 和上面说的又不一致，感觉思路有点乱，并且这个举例也没有具体的结果的例子，写说明是为了让别人看懂。

**Comment by mindjun** [comment]
[test:base] 这个写法是参考 php 中配置的写法，base.test 有点像 test 是 base 的属性，我觉得跟继承不太相关。
举例中的 [testing:base:db] 表示 testing 中的配置可以继承 base 和 db， 举个例子，就像是 testing 是 base 和 db 的子类，所以 testing 可以使用 base 和 db 中的配置。

**Comment by wingfish** [comment]
我宁愿选择 base:test  ，来表示 test 继承自 base这样的说明，php 在很多地方不是好的参考，不能用一个地方看到的就直接使用，这个要讨论的。
对举例我的疑问点是两个：
1 你们的行文都很谨慎，包括前后文，前面描述的和举例的是不一样的，这个是写技术说明的大忌
2 多重继承在实际开发中有必要么？

**Comment by mindjun** [comment]
好的，继承的形式我们再讨论下。
1 我修改下前面的描述，现在的描述不太一致。
2 多重继承是想解决多个环境的配置中，配置项重复写的问题。

**Comment by mindjun** [comment]
讨论后决定不采用继承形式的配置文件读取，关闭该 issue。
