### ISSUE TITLE
update_query, update query params in url

### ISSUE THREAD

**Issue by mindjun** [chinapnr/fishbase#121]
## 背景
- 更新 `get` 请求的数据，返回更新后的请求 `url`

## 步骤
- 使用`urllib.parse`对`url`参数进行处理

## 举例
```python
>>> url = 'https://www.baidu.com/s?ie=UTF-8&wd=fishbase'
>> add_url = {'version': 'v2'}
>>> add_query_to_url(url, add_url)
"https://www.baidu.com/s?ie=UTF-8&wd=fishbase&version=v2"
```

**Comment by wingfish** [comment]
什么叫做：url处理中需要在原来query参数的基础上添加一个query参数
这个话看不太懂。

**Comment by mindjun** [comment]
没有说清楚，意思是：在操作 url 的时候，需要在 query 参数中添加一个参数。

**Comment by mindjun** [comment]
1 好的，我马上更新
2 嗯，目前我们的 issue 都是 review 才继续做的
3 这么描述还是不太清楚，更新为： 更新 get 请求的数据，返回更新后的请求 url
