### ISSUE TITLE
fish_project，init_project_by_yml 方法改进

### ISSUE THREAD

**Issue by oneheartyang** [chinapnr/fishbase#135]
# 通过配置文件初始化一个 project 方法

init_project_by_yml(project_config=None, dist=None) 

其中 project_config 要求 yml 必须满足如下结构, 其中 project, tree 节点必须存在.实际使用中 project 这个节点不一定有, 需要支持 project 为可选配置项

```python
 # define yml string
    package_yml = '''
       project: hellopackage
       tree:
           - README.md
           - requirements.txt
           - setup.py
           - MANIFEST.in
           - hellopackage: # project name
           - __init__.py
           - test: # unittest file
           - __init__.py
           - demo: # usage demo
           - __init__.py
           - doc: # documents
       '''
```

**Comment by iTaa** [comment]
接受建议，后续会考虑更新

**Comment by itaa** [comment]
请 @miaotianshi 跟进下这个 issues ，具体需求可以找 @oneheartyang 了解

**Comment by miaotianshi** [comment]
@oneheartyang project字段，是建立项目的总文件夹名，所以这个不应该做缺省。这个函数的逻辑是，指定project，如果没指定dist就在当前目录下，新建名为project的文件夹，如果指定dist，就在dist目录下建project指定名字的文件夹。个人认为这个逻辑还是比较清晰的，之前沟通的通过dist来决定project字段的做法，并不是一个清晰的方式。整个目录配置参数不应该生成目录所在路径做耦合。
