### ISSUE TITLE
fish_data, 增加判断身份证号码是否有效的函数

### ISSUE THREAD

**Issue by wingfish** [chinapnr/fishbase#137]
作为 fakedata 项目需要，能够验证输入的身份证号是否符合校验规则。

第一步先进行身份证号本身的校验计算，之后会考虑合法性，比如地区码、出生年月等的校验。

按照中华人民共和国国家标准GB11643-1999规定中华人民共和国公民身份号码校验码的计算方法即为ISO 7064:1983.MOD 11-2校验码计算法。

32 01 24 19870101 00 1 X

1：32，2：01，3：24，4：19870101，5：00，6：1，7：X

1 - 3 分别代表 省(直辖市、自治区)/市(自治州)/区县
4 代表出生年月日
5 代表派出所代码
6 代表性别 奇数为男、偶数为女
7 为校验码 与前17位计算所得结果对比校验码是否合法

校验算法参考：https://www.wikiwand.com/zh/%E6%A0%A1%E9%AA%8C%E7%A0%81

1. 17位数字本体码加权求和公式 
　　S = Sum(Ai * Wi), i = 0, ... , 16 ，先对前17位数字的权求和 
　　Ai:表示第i位置上的身份证号码数字值(0~9) 
　　Wi:7 9 10 5 8 4 2 1 6 3 7 9 10 5 8 4 2 （表示第i位置上的加权因子）

2. 计算模 
　　Y = mod(S, 11)

3. 根据模，查找得到对应的校验码 
　　Y: 0 1 2 3 4 5 6 7 8 9 10 
　　校验码: 1 0 X 9 8 7 6 5 4 3 2

根据网上代码，原始出处 https://zhuanlan.zhihu.com/p/24449773 ：

```python
import re

IDCARD_REGEX = '[1-9][0-9]{14}([0-9]{2}[0-9X])?'

def is_valid_idcard(idcard):
    if isinstance(idcard, int):
        idcard = str(idcard)

    if not re.match(IDCARD_REGEX, idcard):
        return False

    items = [int(item) for item in idcard[:-1]]

    ## 加权因子表
    factors = (7, 9, 10, 5, 8, 4, 2, 1, 6, 3, 7, 9, 10, 5, 8, 4, 2)

    ## 计算17位数字各位数字与对应的加权因子的乘积
    copulas = sum([a * b for a, b in zip(factors, items)])

    ## 校验码表
    ckcodes = ('1', '0', 'X', '9', '8', '7', '6', '5', '4', '3', '2')

    return ckcodes[copulas % 11].upper() == idcard[-1].upper()
```

进行修改和调整。

**Comment by wingfish** [comment]
/fishbase/fish_data.py  包括主要逻辑
/demo/demo_data.py 包括 demo 程序
/test/test_data.py 包括 unittest 程序，请补充

**Comment by iTaa** [comment]
已补充单元测试并修复了一下小问题
