### ISSUE TITLE
fish_data, 输入身份证的省份、城市、地区信息，返回地区编号

### ISSUE THREAD

**Issue by wingfish** [chinapnr/fishbase#139]
功能说明：
1 输入包含省份、城市、地区信息的内容，返回地区编号，也就是身份证编码中的前6位内容。比如输入 北京市，返回 110000，输入 北京市宣武区，返回 110104。
2 返回两个内容，第一个数字，表示有多少内容，第二列表，用元素列出。

函数名：
get_zonecode_by_area()

输入：
area_str，要查询的区域，字符串
match_type，查询匹配模式， ‘EXACT’ 严格匹配，默认；‘FUZZY’ 任意匹配
result_type，返回结果数量类型，'LIST' 返回列表，默认；'SINGLE_STR' 单一字符串 
输出：
zonecode：区域代码，6位，包含区域字串，一个记录一个 tuple (a, b)，然后组成 list 返回

主要流程：

1. 建立数据库连接
2. 建立游标
3. 根据查询条件，拼接sql
4. 获得sql 查询内容
5. 对查询内容进行整理
6. 返回结果

---
增加功能点：
如果结果超过20条，只返回前20条记录
设定搜索匹配模式参数，严格或者模糊
返回结果数量，默认list，可以设置返回单一字符串，也就是结果中的第一个

**Comment by mindjun** [comment]
1 参考 [中华人民共和国民政部官网](http://www.mca.gov.cn/article/sj/xzqh/2018/)，这个`中华人民共和国国家标准 GB/T 2260 行政区划代码`，区划代码每年都会变的
2 并且根据省份、城市、地区信息可能会返回多个值的，建议修改接口为：输入身份证编码中的前6位内容，返回省份、城市、地区信息，这样是否更加合理。

**Comment by wingfish** [comment]
这个函数的设计还没写完，身份证相关查询函数会有一些列。
实际使用场景之一是在 fakedata这里，是需要输入上海、北京，这样，然后生成符合规则的身份证号。所以是需要先根据用户规则输入的地域信息，提供6位地域编码给到后面，来生成身份证号。

**Comment by mindjun** [comment]
身份证相关查询的话，能考虑到的有：
1 输入省份、城区信息，市、地返回区划代码，如果是为了生成一个 6 区划代码的话，建议使用某一特定版本的 `GB/T 2260 行政区划代码` 就可。
2 输入身份证前 6 位区划代码，返回省份、城市、地区信息。
3 输入性别，返回特定的身份证号。
4 输入出生年月日信息，返回身份证号，还可以提供年龄是否大于 18 岁的输入选项。
5 输入一个身份证号，返回改身份证号是否符合规则。

**Comment by wingfish** [comment]
收到。

网上直接支持 gbt 2260的https://github.com/cn/GB2260.py 太老了，4年前更新的，我现在用一个比较新的数据库，还好，从 fakedata 角度来说，有些地方不一致问题不大，fakedata 一般到二级城市就足够了，毕竟我们不是做真的身份证验证，那个就不属于这个产品序列了。

这个函数先完成输入省份、城市、地区信息中的若干，返回6位代码，为后面做准备。
但是 fishbase 这里的逻辑还是属于非 fakedata，所以不会去生成 fake 身份证号，这是另外一个项目来进行的，生成身份证验证码、判断身份证是否校验正确（已经实现，你说的第五点）等，是在 fishbase 这里，属于公共逻辑。生成一个随机的有效日期，包括根据年龄生成一个符合该年龄的有效日期，属于 fishbase date 这里。

**Comment by wingfish** [comment]
Python 2.7 ut 没有通过，暂时忽略

**Comment by wingfish** [comment]
2018.12.18  代码优化如下

```python
    values = []

    if match_type == 'EXACT':
        values = sqlite_query('fish_data.sqlite',
                              'select zone, note from cn_idcard where note = :area', {"area": area_str})
    if match_type == 'FUZZY':
        values = sqlite_query('fish_data.sqlite',
                              'select zone, note from cn_idcard where note like :area', {"area": '%' + area_str + '%'})

    # result_type 结果数量判断处理

    if result_type == 'LIST':
        # 如果返回记录多，大于 20 项，只返回前面 20 个结果
        if len(values) > 20:
            values = values[0:20]

        return values

    if result_type == 'SINGLE_STR':
        if len(values) == 0:
            return ''
        if len(values) > 0:
            value_str = values[0][0]
            return value_str
```
