### ISSUE TITLE
fish_common, optimize function name

### ISSUE THREAD

**Issue by mindjun** [chinapnr/fishbase#152]
整理发现 fish_common 中如下命名可优化：

- 类名一般使用名词，例如 `GetMD5` 可优化为 `MD5`, `GetSha256` 可优化为 `SHA256`

- `splice_url_params`  将 `splice` 替换为 `join` 更 pythonic

- `sorted_list_from_dict` 从实现来看，更像是 `get_sorted_values_from_dict`

- `is_contain_special_char` 改为 `has_special_char` 更简洁

- `if_any_elements_is_space` 改为 `has_space_element`

- `remove_duplicate_elements` 改为 `get_distinct_elements`

- `sorted_objs_by_attr`  改为 `sort_objs_by_attr`

- `get_group_list_data` 从实现来看，更像是对数据分页，命名为 `paging` 更合适

- `if_any_elements_is_letter` 参考 `Python`, 命名为 `isalpha`

- `transform_hump_to_underline`  驼峰命名应该为 `CamelCase`, 命名修改为 `camelcase_to_underline`

函数命名，欢迎大家提出修改意见。

**Comment by iTaa** [comment]
这样的改动算是很大的改动了，可以先在 1.x.x 更新 ，保留之前的命名，加上 DeprecationWarning ，在 2.x.x 时候可以彻底废弃老的写法。

**Comment by mindjun** [comment]
好的，我将在随后的版本中提交更新，添加 `DeprecationWarning ` 和 `fish_` 加以区别标准库。
