### ISSUE TITLE
fish_common, 使用 pathlib 包替换 os.path

### ISSUE THREAD

**Issue by mindjun** [chinapnr/fishbase#212]
pathlib 是 python 3.x 时代引入的新的专门更加优雅的处理比较麻烦的路径拼接、文件是否存在、路径是否存在等操作系统文件路径相关的 Python 官方函数。
计划替换 fish_common 中的如下方法：
1 conf_as_dict
2 find_files
3 yaml_conf_as_dict

**Comment by iTaa** [comment]
pathlib 针对路径的处理更加优雅，补充官方文档连接如下：
https://docs.python.org/3/library/pathlib.html
