### ISSUE TITLE
银行卡，身份证依赖的信息从 sqlite 及 csv 中读取会造成 IO 过多

### ISSUE THREAD

**Issue by sh-xin-guo** [chinapnr/fishbase#232]
现在生成银行卡，身份证信息等需要从 sqlite 和 csv 中读取地区信息等，每次执行函数都会进行一次IO。在 parrot 等需要批量生成数据的时候，会造成大量 io ，导致 cpu 及内存占用迅速上升，在生成百万级别数据时会直接造成应用奔溃。

建议这些信息直接使用静态变量的形式存放。

**Comment by wingfish** [comment]
这个提的挺好的，我写过一些python 缓存的介绍，开发团队看一下，有没有帮助。

**Comment by itaa** [comment]
好的，我们试一下

**Comment by mindjun** [comment]
使用 `lru_cache`，测试得到生成速率为 5000/s
