### ISSUE TITLE
日志文件格式优化

### ISSUE THREAD

**Issue by rexyan** [chinapnr/fishbase#240]
希望对目前日志文件名称支持可配置化。目前为格式为 application_name.log.date

**Comment by mindjun** [comment]
- 目前文件命名格式: `application_name.log.date` 中的 `application_name.log` 为 `set_log_file(local_file=None)` 的参数 `local_file`，`fishbase` 只进行后缀日期的添加。
- 为 `set_log_file` 提供可选参数 `file_name_format` 进行配置，默认值为 "%project_name-%log-%date",调用者可根据 `peoject_name`, `log` 和 `%date` 对日志文件名进行配置。
- 举例如下：
```
python
>> set_log_file(file_name_format='%project_name-%log-%date')
project_name.log.2019-07-16
>> set_log_file(file_name_format='%project_name-%date-%log')
project_name.2019-07-16.log
```

**Comment by rexyan** [comment]
已完成
