### ISSUE TITLE
fishbase 提供生成二维码的方法, 要求可以自定义样式

### ISSUE THREAD

**Issue by oneheartyang** [chinapnr/fishbase#246]
目前h5 项目都有生成二维码做分享的需求, 建议做成一个服务

**Comment by itaa** [comment]
这个功能有一定的通用性，需要评估一下生成二维码的功能需要哪些第三方依赖，会不会很大。

**Comment by itaa** [comment]
评估了几个模块，基本都依赖 Pillow , 3MB 以上, 且模块封装的功能基本都比较完善，建议直接使用，不易封装至 fishbase 
参考如下：
[python-qrcode](https://github.com/lincolnloop/python-qrcode)
[MyQR](https://github.com/sylnsfar/qrcode)
