### ISSUE TITLE
改写get_md5方法，新增“文件”、“大文件”的MD5获取功能

### ISSUE THREAD

**Issue by iTaa** [chinapnr/fishbase#26]
相关代码如下：

```python
def get_md5(string, mode='S'):
    """
    获取MD5方法
    :param string: 待hash的字符串，或者是文件的路径，
                如果是文件路径的时候需要设置mode='F'
    :param mode: 模式，'S', 获取字符串的MD5
                'F', 传入的str需要是文件的路径
                'B', 大文件的MD5,传入的str需要是文件的路径
    :return: 32位小写MD5值
    """
    if mode.upper() == 'S':
        return _get_str_md5(string)
    if mode.upper() == 'F':
        return _get_file_md5(string)
    if mode.upper() == 'B':
        return _get_big_file_md5(string)


def _get_str_md5(string):
    """
    获取一个字符串的MD5值
    :param string 待hash的字符串
    :return: 32位小写MD5值
    """
    m0 = hashlib.md5()
    m0.update(string.encode('utf-8'))
    result = m0.hexdigest()
    return result


def _get_file_md5(file_path):
    """
    获取一个文件的MD5值
    :param file_path 待hash的文件路径
    :return: 32位小写MD5值
    """
    with open(file_path, 'rb') as f:
        md5obj = hashlib.md5()
        md5obj.update(f.read())
        hash_o = md5obj.hexdigest()
        return hash_o


def _get_big_file_md5(file_name):
    """
    获取一个较大文件的MD5值
    :param file_name 待hash的文件路径
    :return: 32位小写MD5值
    """
    if not os.path.isfile(file_name):
        return
    hash_o = hashlib.md5()
    f = open(file_name, 'rb')
    while True:
        b = f.read(8096)
        if not b:
            break
        hash_o.update(b)
    f.close()
    return hash_o.hexdigest()
```

**Comment by wingfish** [comment]
很好，我看看是否用类方法来实现会更加优雅一点，现在这样传参数的话，有点不直观。

**Comment by wingfish** [comment]
`class GetMD5(object):
    """
    获取MD5方法
    :param : 待hash的字符串，或者是文件的路径，
                如果是文件路径的时候需要设置mode='F'
    :param : 模式，'S', 获取字符串的MD5
                'F', 传入的str需要是文件的路径
                'B', 大文件的MD5,传入的str需要是文件的路径
    :return: 32位小写MD5值
    """

    @staticmethod
    def str(string):
        """
        获取一个字符串的MD5值
        :param string 待hash的字符串
        :return: 32位小写MD5值
        """
        m0 = hashlib.md5()
        m0.update(string.encode('utf-8'))
        result = m0.hexdigest()
        return result

    @staticmethod
    def file(file_path):
        """
        获取一个文件的MD5值
        :param file_path 待hash的文件路径
        :return: 32位小写MD5值
        """
        with open(file_path, 'rb') as f:
            md5obj = hashlib.md5()
            md5obj.update(f.read())
            hash_o = md5obj.hexdigest()
            return hash_o

    @staticmethod
    def big_file(file_name):
        """
        获取一个较大文件的MD5值
        :param file_name 待hash的文件路径
        :return: 32位小写MD5值
        """
        if not os.path.isfile(file_name):
            return
        hash_o = hashlib.md5()
        f = open(file_name, 'rb')
        while True:
            b = f.read(8096)
            if not b:
                break
            hash_o.update(b)
        f.close()
        return hash_o.hexdigest()`

简单的来说，用类方法会更加优雅，调用的时候如下

`    print('string md5:', GetMD5.str('hello world!'))
    print('file md5:', GetMD5.file(get_abs_filename_with_sub_path('test_conf', 'test_conf.ini')[1]))
    print('big file md5:', GetMD5.big_file(get_abs_filename_with_sub_path('test_conf', 'test_conf.ini')[1]))`

这个要比传入代表不用意义的字符作为某种类型的调用要好

**Comment by wingfish** [comment]
原来的大文件这里的写法是有问题的，没有做基本的放错处理，python 中的打开操作文件原则上是一定要用 with 方法的。我参考了一些资料，用迭代器来代替原来的循环方式，来避免 while-break 这样的操作。

```python
    @staticmethod
    def big_file(filename):
        """
        获取一个大文件的 MD5 值

        :param:
            * (string) filename 需要进行 hash 的大文件路径
        :return:
            * (string) result 32位小写MD5值
        """
        md5 = hashlib.md5()
        with open(filename, 'rb') as f:
            for chunk in iter(lambda: f.read(8192), b''):
                md5.update(chunk)

        result = md5.hexdigest()
        return result
```

**Comment by wingfish** [comment]
基本完成。单元测试通过。
