### ISSUE TITLE
init_project_by_yml 用户目录会报错

### ISSUE THREAD

**Issue by coderQuan** [chinapnr/fishbase#284]

**Comment by coderQuan** [comment]
<img width="718" alt="WX20200918-153509@2x" src="https://user-images.githubusercontent.com/16987105/93569815-ad9ee780-f9c4-11ea-82de-984a3521c070.png">

**Comment by wingfish** [comment]
收到，我们看一下哪里出问题了，并且为什么 ut 没有查出来。

**Comment by itaa** [comment]
排查了一下，原因是新版的yaml.load()需要指定Loader。 请 @halfapple 看看优化一下。

**Comment by halfapple** [comment]
```
param1 = {'0': 100}
print(param1['0'])  # 100

param2 = '0123456'
print(param2[0])  # '0'

print(param2['0'])  # TypeError: string indices must be integers
```

@coderQuan ，
从目前的截屏信息看，

程序 105 行出现了警告信息：calling yaml.load() without Loader=... is deprecated （这个是由于高版本的 yaml 希望可以用速度更快 CLoader 来执行导致，我们这里会在下一个版本中优化）

程序 106 行首次出现了错误信息：string indices must be integers，在上一行发生警告的情况下，程序继续对 yml_data 做了读取操作，导致该 TypeError 发生，类似这里的 param2['0'] 的报错。我们会在下一个版本中优化，比如做一些安全检查。

你可以再检查下配置文件：server-project-template.yaml ，注意其中的空格。或者把配置文件贴出来，方便我们继续跟踪排查。


非常感谢 :-)

**Comment by coderQuan** [comment]
发现文件不存在也会报同样的错误。所以使用绝对路径就可以了。谢谢🙏
<img width="720" alt="WX20200929-090729@2x" src="https://user-images.githubusercontent.com/16987105/94501013-58b86800-0233-11eb-9b20-1a37034268f9.png">
