### ISSUE TITLE
fish_base 的版本描述，应该为 __version__= 'xxx'

### ISSUE THREAD

**Issue by iTaa** [chinapnr/fishbase#30]
根据PEP 396的规范, version的版本需要写到__version__属性下。
[PEP 396官方链接](https://www.python.org/dev/peps/pep-0396/#specification)

> 3. When a module (or package) includes a version number, the version SHOULD be available in the \_\_version\_\_ attribute.

**Comment by wingfish** [comment]
所言甚至，这个早起学 python 时候写的，弄了半吊子。

现在在 __init__.py 中
```python
__version__ = '1.0.11'
```

setup.py 中
```python
from setuptools import setup
from fish_base import __version__

setup(
    name='fish_base',
    version=__version__,
```
