### ISSUE TITLE
check_obj_length，合并issue #28 #35，检查Python对象长度是否在限定范围内

### ISSUE THREAD

**Issue by mindjun** [chinapnr/fishbase#53]
## 背景
- #28  #35  #两个问题都是判断python对象是否在限定长度内，可以进行合并

##  步骤
- 方法包含默认参数，`min_len=0, max_len=sys.maxsize`，分别表示最小长度为0，最大长度为当前环境支持最大Int值
- 使用 `hasattr(obj, '__len__')` 方法判断校验对象是否能取长度值，不能则返回 `TypeError`
- 使用 `min_len < len(obj) < max_len`判断长度

## 举例
 ```python
>>> list1 = 'abdaca'
>>> int1 = 12
>>> check_obj_length(list1)
True
>>> check_obj_length(list1, min_len=10, max_len=20)
False
>>> check_obj_length(int1)
TypeError: object type of <class 'int'> has no len()
```

**Comment by iTaa** [comment]
在python中检测对象的长度的限制，单独写一个函数感觉没有必要，因为python支持`10 < len(obj) < 20`这种写法，对比起来更简单些：
```python
>>>list1 = 'abdaca'
>>># 方法1
>>>10 < len(list1) < 20
False
>>># 方法2
>>> check_obj_length(list1, min_len=10, max_len=20)
False
```

**Comment by mindjun** [comment]
考虑用户使用场景，判断长度时使用`10 < len(obj) < 20`更加便捷。

**Comment by iTaa** [comment]
好的，那就把这个issue关闭了
