### ISSUE TITLE
fish_common.GetMD5 类的改进

### ISSUE THREAD

**Issue by mindjun** [chinapnr/fishbase#57]
## 背景
类 `fish_common.GetMD5` 中方法`file`和`big_file` 重复，另外对于文件大小的划分没有标准，多大为大文件？

## 建议
计算文件的`md5`值时均使用分块读入，使用`big_file`替换`file`

**Comment by iTaa** [comment]
GetMD5时候使用分块处理是为了防止文件过大，占爆内存，这里可以将`file`和`big_file`合并，是否可以考虑选择一个合适的默认值作为大小文件的区分线，超过这个线自动分块？

**Comment by wingfish** [comment]
首先这两个方法就是针对大小不一样的文件，不要断言就是重复，实际上你也知道关键是多大的文件算大文件。

为什么我没有设置一个值，1 这个和服务器内存有关，所以存在一个最佳实践的问题，是比较复杂的 2 当时主要是修改了大文件处理的一些方法，使用 with 来减少错误。

很多时候，需要签名的文件是不大的，但是的确也有我们传统理解上的大文件，所以这个建议，我是不能赞同的。

更好的做法是，salt 的引入、更多的 md5计算方法等来增强。

**Comment by mindjun** [comment]
参考[MD5算法](https://zh.wikipedia.org/wiki/MD5)应用场景：
1. 文件应用场景，在文件传输提供一定的可靠性，校验是否是同一个文件；
2. 字符串应用时一般会加上一组随机字符串，防止碰撞解密。

添加 salt，更适用于字符串场景，故考虑在`GetMD5.string(s, salt=None)`添加默认参数，salt，当输入参数不为空时添加`salt`计算摘要。
