### ISSUE TITLE
GetBase64 获取字符串、文件的base64编码

### ISSUE THREAD

**Issue by mindjun** [chinapnr/fishbase#59]
## 背景
- `Base64`是网络上最常见的用于传输8Bit字节码的编码方式之一
- 我们的服务中涉及到文件的传输时常使用 `Base64` 进行编码

## 步骤
- 参考 `GetMD5` 实现
- 编写类，提供`file`和`string`，两个静态方法，分别对`file`和`string`进行`Base64`编码

## 举例
```python
>>> GetBase64.string('hello world')
b'aGVsbG8gd29ybGQ='
>>> GetBase64.file('./test.png')
b'IyEvYmluL2Jhc2gKCmNkIC9yb290L3d3dy9zaW5nbGVfcWEKCm5vaHVwIC9yb290L2FwcC9weXRob24zNjIvYmluL2d1bmljb3JuIC1jIGd1bmljb3JuLmNvbmYgc2luZ2xlX3NlcnZlcjphcHAK'
```

**Comment by iTaa** [comment]
Base64和MD5不同，MD5是一个计算hash值的方法，是不可逆的，可以用GetMD5； Base64是一种编码方式，有 encode 和 decode 之分，大多数的实现方式是写一个base64的类，然后`base64.encode()` `base64.decode()`， base64类python本身已经自带这个包了，感觉没有必要重写

**Comment by mindjun** [comment]
添加`GetBase64`类主要用到获取文件的编码，添加`decode`方法可以将类名修改为：`Base64`，使用`Base64.decode(s)`进行解码

**Comment by iTaa** [comment]
这样会好一点，可以加上去了
