### ISSUE TITLE
is_dict_value_none，检查字典中是否有空的值

### ISSUE THREAD

**Issue by mindjun** [chinapnr/fishbase#62]
## 背景
- `post`请求中需要判断`body`的参数字典是否存在空的值
- 空的值包括空字符换、空数组，None等`Python`中`if`判断为`False`的值

## 步骤
- 使用 `dict.keys()` 方法取得所有的键，根据`dict.get()`来进行判断是否值为空

## 举例
```python
>>> dict1 = {'A_key': 'A_value', 'a_key': 'a_value', 'z_key': 'z_value'}
>>> is_dict_value_none(dict1)
False
>>> dict1.update({'non_str':''})
>>> is_dict_value_none(dict1)
True
>>> dict1.update({'non_list':[]})
>>> is_dict_value_none(dict1)
True
```

**Comment by iTaa** [comment]
函数名`is_dict_value_none `感觉不是很好，因为是判断字典里是否包含`None `和 `空值`，可以参考 `fish_common.if_any_elements_is_space` 来命名，或者直接在这个函数里扩展

**Comment by mindjun** [comment]
建议可以在`fish_common.if_any_elements_is_space`中进行扩展：
- 支持序列类型，`list、tuple` 
- 映射对象， `dict`
