### ISSUE TITLE
remove_duplicate_elements，删除列表中的重复元素

### ISSUE THREAD

**Issue by mindjun** [chinapnr/fishbase#63]
## 背景
- 需要删除列表中的重复元素，避免重复计算
- 例如在权限控制中，需要删除一个角色权限列表中的重复权限

## 步骤
- 将`list`转换成`set`，去除掉重复元素，再转换成`list`返回

## 举例
```python
>>> list1 = ['a', 1, 2, 'c', 'd', 'sting', 2, 'd', 'string']
>>> remove_duplicate_elements(list1)
[1, 2, 'd', 'c', 'a', 'string']
```

**Comment by iTaa** [comment]
使用set转换有两个问题：
1. 并不是所有的`list`都可以直接转为`set`, 只有`list`中所有的元素都是`hashable`的时候才可以转换，如：
	```python
	>>> list1 = ['a', 1, 2, 'c', 'd', 'sting', 2, 'd', 'string',[1,2]]
	>>> set(list1)
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	TypeError: unhashable type: 'list'
	```
2. 转换后的`list`是无序的

**Comment by mindjun** [comment]
1. 对于`Python`中的标准数据类型是否是重复的，需要分情况讨论：
- 不可变数据（3 个）：Number（数字）、String（字符串）、Tuple（元组）
- 可变数据（3 个）：List（列表）、Dictionary（字典）、Set（集合）

    其中不可变数据的`hash`值在其生命周期中是不可变的，因此可以使用`set`去除重复的项
    对于可变数据，`List`是有序的，`Dictionary`、`Set`是无序的，如果需要判断`List`是否相同，需要顺序与内容一致，`Dictionary`、 `Set`则需要内容一致即可。
    如果需要判断`unhashable`对象是否重复，需要分情况讨论，但是我认为对于不可变对象的去重没有太大应用场景，在程序中判断当出现`unhashable`对象时抛错。

    对于可变数据，参考如下举例：

```python
>>> [1,23,4] == [4,1,23]
False
>>> {'1':2, 'a':1} == {'a':1, '1':2}
True
>>> {1,2,3} == {1,3,2}
True
```

2. 参考 `Python`  [set 文档](https://docs.python.org/3/library/stdtypes.html?highlight=set) 说明: `set对象是不同可哈希对象的无序集合。`，因此使用`set`去重的话得到的结果是无序的。
