### ISSUE TITLE
fish_common.splice_url_params 方法的改进

### ISSUE THREAD

**Issue by mindjun** [chinapnr/fishbase#67]
## 背景
- `fish_common.splice_url_params`方法用于拼接`url`的`query`参数
- `Python`内建包[urllib](https://docs.python.org/3.6/library/urllib.html)提供了丰富的方法用于`url`的解析

## 建议
- 可以使用[urllib.parse.urlencode](https://docs.python.org/3.6/library/urllib.parse.html#urllib.parse.urlencode)来进行query参数的拼接
- 同样使用`OrderedDict`来保持字典的顺序

## 举例
```python
>>> dict1 = {'spam': 1, 'eggs': 2, 'bacon': 0}
>>> od = OrderedDict(sorted(dict1.items()))
>>> urllib.parse.urlencode(od)
'bacon=0&eggs=2&spam=1'
```

**Comment by iTaa** [comment]
拼接`url`的`query`参数如果是为了用`requests`做`get`请求可以直接将字典对象放到`params`参数里，无需做拼接操作，参考如下：
```python
def get(url, params=None, **kwargs):
    r"""Sends a GET request.

    :param url: URL for the new :class:`Request` object.
    :param params: (optional) Dictionary or bytes to be sent in the query string for the :class:`Request`.
    :param \*\*kwargs: Optional arguments that ``request`` takes.
    :return: :class:`Response <Response>` object
    :rtype: requests.Response
    """

    kwargs.setdefault('allow_redirects', True)
    return request('get', url, params=params, **kwargs)
```
详见：https://github.com/requests/requests/blob/master/requests/api.py, line 61-72

**Comment by mindjun** [comment]
使用`requests`做`get`请求将`params`时已经向`url`发送了请求，经过与`splice_url_params`方法的提议者沟通，他们只希望拿到`query`的`str`，所以我建议使用`urllib.parse.urlencode`来进行请求参数拼接。
