### ISSUE TITLE
fish_file.check_sub_path_create 方法的改进

### ISSUE THREAD

**Issue by jacsonking** [chinapnr/fishbase#69]
## 背景
* fish_file.check_sub_path_create 方法用于生成必要的文件夹
* 进行单元测试时，单元测试脚本所在文件夹为test；调用该方法的脚本所在文件夹为config，并且test与config目录同级，执行单元测试脚本时，会在test文件夹下生成log文件夹，而log文件夹应与test同级
## 建议
* 修改check_sub_path_create 方法参数sub_path含义为子文件夹长路径
* 在单元测试脚本中修改当前工作目录

**Comment by mindjun** [comment]
根据你的描述，是否是以下的示例：
- test
    - start.py
- config
    - config.py

`start.py`调用`config.py`，你的需求是达到如下效果：
- test
    - start.py
- config
    - config.py
- log

而`fish_file.check_sub_path_create`的功能是： `检查当前路径下的某个子路径是否存在, 不存在则创建`，因此该方法的功能跟你的需求是不符合的。

**Comment by jacsonking** [comment]
是的
