### ISSUE TITLE
get_group_list_data， 获取列表偏移量数据

### ISSUE THREAD

**Issue by mindjun** [chinapnr/fishbase#74]
## 背景
-  `web`中需要根据分页获取数据
-  设计分页数据时，需要根据页码数以及每页数据量获取相应的数据

## 步骤
-  提供所有的数据：`all_records`，页码数：`page_number`和每页数据量：`page_size`作为参数
-  `page_number`默认值为`1`， `page_size`默认值为`10`
-  `all_records`类型是列表，`page_number`和`page_size`类型为整形

## 举例
```python
>>> all_records = [1,2,3,4,5]
>>> get_list_offset_data(all_records)
 [1, 2, 3, 4, 5]
>>> all_records1 = list(range(100))
>>> get_list_offset_data(all_records1, page_number=5, page_size=15)
[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74]
>>> get_list_offset_data(all_records1, page_number=7, page_size=15)
[90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
```

**Comment by iTaa** [comment]
从函数的功能上来看，并不是获取偏移量数据的，而是先将`list`进行`grouping`操作，再获取`subgroup`的，因此函数名和参数需要调整一下。
另：偏移量的操作可以参考[file.seek()](https://github.com/python/cpython/blob/master/Lib/typing.py#L1508)的用法
