### ISSUE TITLE
get_obj_attr_dict，获得对象的属性，并以字典的形式返回

### ISSUE THREAD

**Issue by mindjun** [chinapnr/fishbase#76]
## 背景
- `sqlalchemy`查询结果是一个`orm`的对象，在取到`orm`对象之后需要取出表对象的字段属性
- 如果使用特定表字段作为属性取值的做法不通用

## 步骤
- 将对象中的`public`属性取出
- 根据`getattr`获得对象的属性

## 举例
```python
>>> class Table(object):
        def __init__(self, a, b, c):
            self._d = 12
            self.a = a
            self.b = b
            self.c = c

>>> table = Table(1,2,3)
>>> get_obj_attr_dict(table)
{'a': 1, 'b': 2, 'c': 3}
```

**Comment by iTaa** [comment]
python 中获取对象的属性不是可以通过`__dict__`直接拿到吗？为什么还要实现这个方法？只是为了要去除私有属性(`_`下划线开头的），参考如下：
```python
>>> class Table(object):
        def __init__(self, a, b, c):
            self._d = 12
            self.a = a
            self.b = b
            self.c = c

>>> table = Table(1,2,3)
>>> table.__dict__
{'_d': 12, 'a': 1, 'b': 2, 'c': 3}
```

**Comment by wingfish** [comment]
楼主记住：python 中一切揭示对象，所以对象本身的很多属性等都是可以被访问到的，我们有时候就说这是反射机制。有了这样的特性，python 才变得异常强大和灵活，我们可以动态的获得很多运行时候的信息。其实这也是注入 JR，zion 项目的设计思路，所创造的对象动态的去控制，我们才可以不限制业务逻辑，否则只能输入1输出1，是固定的逻辑。

**Comment by mindjun** [comment]
因为在业务逻辑中遇到想要将对象转换成字典的需求，所以想要将该方法抽象，在写的时候没有考虑到`__dict__`方法。对象本身的属性都可以被访问到，这样就没有单独抽象该方法的必要了。
