### ISSUE TITLE
新增目录结构生成功能

### ISSUE THREAD

**Issue by iTaa** [chinapnr/fishbase#82]
## 新增目录结构生成功能
1. 根据配置文件(YML格式)生成目录结构
2. 创建默认的配置文件，支持python web项目的目录结构和python module的目录结构
## 应用场景
1. saturn for python
2. 其他需要批量生成目录结构的场景

**Comment by wingfish** [comment]
saturn 并不完全是 web 开发框架，是一种约束规范方式
yaml 格式之后要补充一下
