### ISSUE TITLE
封装 activemq 操作

### ISSUE THREAD

**Issue by mindjun** [chinapnr/fishbase#86]
## 封装activemq操作
- 使用`stomp`连接`activemq`并封装相关操作

## 应用场景
- 需要使用`python`连接`activemq`的项目中

**Comment by wingfish** [comment]
具体封装一些什么操作呢？
是不是要起一个新的子类名称？

**Comment by mindjun** [comment]
目前我们先封装一些基础的功能，例如：`connect、set_listener、send、disconnect`，后续根据需求会进行进一步扩展，
考虑新建一个文件命名为，`fish_mq.py`，建立子类实现 `ActiveMQ`，后续可以扩展`RabbitMQ`等
