### ISSUE TITLE
get_ramdon_datetime， 生成随机的时间

### ISSUE THREAD

**Issue by mindjun** [chinapnr/fishbase#87]
## 背景
- 向数据库中填充数据时需要生成一些随机时间
- 随机时间需要是当年、当月的一个随机时间

## 步骤
- 获取当年和当月的天数
- 使用`random`生成一个随机的天数
- 使用`datetime.timedelta`将当年、当月的开始天数加上随机的时间得到结果

## 举例
```python
>>> get_ramdon_datetime(this_year=True)
datetime.datetime(2018, 7, 15, 20, 8, 54)
>>> get_ramdon_datetime(this_month=True)
datetime.datetime(2018, 7, 14, 2, 45, 8)
```

**Comment by iTaa** [comment]
参数`this_year `和`this_month `同时为`True `的时候是不是应该默认取当月的？这两个能否合并成一个参数？

**Comment by mindjun** [comment]
参数`this_year`和`this_month`同时为`True`的时候应该默认取当月的时间，另外如果合并为一个参数的话怎么区分当月还是当年呢？
我在考虑将这两个方法写进一个类，作为静态方法，方便扩展，例如想要获取某年的一个随机时间，未来的一个随机时间等。
