### ISSUE TITLE
建议封装常见正则模块

### ISSUE THREAD

**Issue by rexyan** [chinapnr/fishbase#91]
### 背景
将 Python 开发中常用的正则表达式进行封装

### 举例
```
class Validate:
      reglist = {
          'CH': r'[^\u0000-\u00FF]*',                                                # 纯文字
}
```
可提供check等方法，调用的时候传入要校验的字符串，要校验的类型即可

**Comment by iTaa** [comment]
很好的建议，正则在使用时很容易出错，封装到一起统一维护会好一些，我们后续会收集一下大家常用的正则，封装起来。或者你这里有没有更多的例子，可以贴出来参考？

**Comment by wingfish** [comment]
所有参数检查还是建议单独一个模块，我看到目前 jman 里面还是有很多是参数检查，所以要区分一下正则是用在参数检查还是其他场景

**Comment by mindjun** [comment]
这个正则的建议在 #92 中有提到，考虑正则也属于参数检查的一种情况。

**Comment by wingfish** [comment]
需要的话，就可以关闭这个 issue，还是作为 feature？

**Comment by rexyan** [comment]
> 有很多地方会用到正则表达式，可以将常用的进行封装集成在fishbase中
> 
> 这个话总是哪里怪怪的，修改如下，1 写东西慢一点 2 不能过于口语化 3 多看书
> 
> 将 Python 开发中常用的正则表达式进行封装

好的

**Comment by rexyan** [comment]
简单实现如下。代码可通过下方链接下载。支持自定义类型拓展，正则表达式拓展。支持参数三种传入方式。可能不是最好的实践方案，仅供大家参考。
![](https://raw.githubusercontent.com/rexyan/warehouse/master/xxxxahasdnasdhore.png)

[示例代码](https://raw.githubusercontent.com/rexyan/warehouse/master/AgileP-Demo.7z)

**Comment by rexyan** [comment]
后续单独抽取成验证模块，也是可选安装。
