### ISSUE TITLE
读取文件支持多种编码格式

### ISSUE THREAD

**Issue by yanan-wu** [chinapnr/fishbase#94]
### 背景
agbot 读取数据文件和配置文件时，需求需要支持 gbk 和 utf-8 两种编码格式

### 实现
fishbase 中的 csv_file_to_list(csv_filename, deli=',', del_blank_row=True) 和 conf_as_dict(conf_filename) 方法增加默认参数 encoding=None，通过该参数指定读取的目标文件的编码。

**Comment by mindjun** [comment]
在Python2中`open`操作不支持`encoding`，[Python2 open方法](https://docs.python.org/2/library/functions.html?highlight=open#open)，故改操作在`fishbase`中Python3版本支持。
