### ISSUE TITLE
yaml_conf_as_dict, 读取  yaml  配置文件

### ISSUE THREAD

**Issue by mindjun** [chinapnr/fishbase#98]
## 背景
- `YAML`是专门用来编写配置文件的语言，简洁又方便

## 步骤
- 使用内置包`yaml`进行配置文件读取
- 支持编码选择，`encoding`
- 返回保序字典，`OrderedDict`
- 该方法用配置文件路径 `file_path` 和编码 `encoding` 作为参数，返回 `yaml` 配置组成的保序字典 `OrderedDict`

## 实现
```python
>>>  conf_path = './config.yaml'
>>> conf_dict = yaml_conf_as_dict(conf_path, encoding='utf-8')
>>> conf_dict
OrderedDict([('nub1', ['admin1', '123456']), ('nb2', ['admin2', '111111']), ('nb3', ['admin3', '222222']), ('time1', datetime.datetime(2018, 4, 18, 13, 59, 43, 100000)), ('date1', datetime.date(2018, 4, 18)), ('name', '测试')])
```

**Comment by wingfish** [comment]
YMAL是专门用来编写配置文件的语言，简洁又方便

这样的描述感觉很不严肃

为什么不是 yaml_as_dict，另外和 yaml_to_dict 有什么区别？

另外，入参、出参，都没有

**Comment by wingfish** [comment]
我们用 issue 来代替详细设计的，所以相关设计，实现都要有的

用 as 还是 to，你们要商量一下，要逐渐统一，一开始总是比较简单，做的复杂了就会考虑一致性问题，这也不能迁就，否则以后哪天修改起来更加麻烦。

**Comment by mindjun** [comment]
好的，以后的 `issue` 会更加详细，`as` 和 `to` 的问题我们再讨论下。
